//request.rest 

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "testUser1",
  "email": "test1@test.com",
  "password": "123456"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "123456"
}

### Google Login
POST http://localhost:3000/auth/google
Content-Type: application/json

{}

### Refresh
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE4MWQwYzQxZTNjODIxNzQ0ZWI4MTgiLCJyYW5kIjo0OTgzOTQsImlhdCI6MTc3MjYyNTE5MCwiZXhwIjoxNzczMjI5OTkwfQ.fQ1DwRUwGPgSfWr1e6XJ7rAiKO0vTvxUZ45L4nmrsYg"
}

### Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE4MWQwYzQxZTNjODIxNzQ0ZWI4MTgiLCJyYW5kIjo0OTgzOTQsImlhdCI6MTc3MjYyNTE5MCwiZXhwIjoxNzczMjI5OTkwfQ.fQ1DwRUwGPgSfWr1e6XJ7rAiKO0vTvxUZ45L4nmrsYg"
}

### Get all recipes (public + owned by user)
GET http://localhost:3000/recipes
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE4MWQwYzQxZTNjODIxNzQ0ZWI4MTgiLCJpYXQiOjE3NzI2MjUyMzUsImV4cCI6MTc3MjYyNjEzNX0.CT1t2iRO47O7QXzrCpQij0CMefFo2CMjxjZJA-_RhTU"

### Create a new recipe
POST http://localhost:3000/recipes
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE4MWQwYzQxZTNjODIxNzQ0ZWI4MTgiLCJpYXQiOjE3NzI2MjUyMzUsImV4cCI6MTc3MjYyNjEzNX0.CT1t2iRO47O7QXzrCpQij0CMefFo2CMjxjZJA-_RhTU"

{
  "title": "Chocolate Cookies",
  "description": "A delicious chocolate cake recipe.",
  "ingredients": ["2 cups flour", "1 cup sugar", "1 cup cocoa powder", "2 eggs"],
  "cookTime": 30,
  "difficulty": "medium",
  "isPublic": false
}


### Get my recipes (owned by user)
GET http://localhost:3000/recipes/my
Authorization: Bearer "PASTE_TOKEN_HERE"

### Get a recipe by ID
GET http://localhost:3000/recipes/69a40fa29a6041eb49ade735
Authorization: Bearer "PASTE_TOKEN_HERE"

### Update a recipe
PUT http://localhost:3000/recipes/69a40fa29a6041eb49ade735
Content-Type: application/json
Authorization: Bearer "PASTE_TOKEN_HERE"

{
  "title": "Updated Chocolate Cookies 2",
  "description": "An even more delicious chocolate cake recipe.",
  "ingredients": ["2 cups flour", "1 cup sugar", "1 cup cocoa powder", "3 eggs"],
  "cookTime": 35,
  "difficulty": "easy",
  "isPublic": false
}

### Delete a recipe
DELETE http://localhost:3000/recipes/69a40fa29a6041eb49ade735
Authorization: Bearer "PASTE_TOKEN_HERE"


### likes

POST http://localhost:3000/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE4MWQwYzQxZTNjODIxNzQ0ZWI4MTgiLCJpYXQiOjE3NzI2Mjc4MzcsImV4cCI6MTc3MjYyODczN30.m8t0TvoX22T5od3CoV6sy2kxIEVGEPJYnmUpc10zSrM

{
  "targetType": "recipe",
  "targetId": "69a82659b404fe4a62d3d6c3"
}

### comments
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE4MWQwYzQxZTNjODIxNzQ0ZWI4MTgiLCJpYXQiOjE3NzI2MzMxNzgsImV4cCI6MTc3MjYzNDA3OH0.6OJIBnVisdKv4PRQAcMtpA356XvfZIxPVwuzMcNzSDI

{
  "targetType": "recipe",
  "targetId": "507f1f77bcf86cd799439011",
  "content": "This recipe looks great!"
}