//request.rest 

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "testUser1",
  "email": "test1@test.com",
  "password": "123456"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "123456"
}

### Refresh
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "PASTE_REFRESH_TOKEN_HERE"
}

### Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "PASTE_REFRESH_TOKEN_HERE"
}

### Get all recipes (public + owned by user)
GET http://localhost:3000/recipes
Authorization: Bearer "PASTE_TOKEN_HERE"

### Create a new recipe
POST http://localhost:3000/recipes
Content-Type: application/json
Authorization: Bearer "PASTE_TOKEN_HERE"

{
  "title": "Chocolate Cookies",
  "description": "A delicious chocolate cake recipe.",
  "ingredients": ["2 cups flour", "1 cup sugar", "1 cup cocoa powder", "2 eggs"],
  "cookTime": 30,
  "difficulty": "medium",
  "isPublic": false
}


### Get my recipes (owned by user)
GET http://localhost:3000/recipes/my
Authorization: Bearer "PASTE_TOKEN_HERE"

### Get a recipe by ID
GET http://localhost:3000/recipes/69a40fa29a6041eb49ade735
Authorization: Bearer "PASTE_TOKEN_HERE"

### Update a recipe
PUT http://localhost:3000/recipes/69a40fa29a6041eb49ade735
Content-Type: application/json
Authorization: Bearer "PASTE_TOKEN_HERE"

{
  "title": "Updated Chocolate Cookies 2",
  "description": "An even more delicious chocolate cake recipe.",
  "ingredients": ["2 cups flour", "1 cup sugar", "1 cup cocoa powder", "3 eggs"],
  "cookTime": 35,
  "difficulty": "easy",
  "isPublic": false
}

### Delete a recipe
DELETE http://localhost:3000/recipes/69a40fa29a6041eb49ade735
Authorization: Bearer "PASTE_TOKEN_HERE"


###

POST http://localhost:3000/likes
Content-Type: application/json
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE

{
  "targetType": "recipe",
  "targetId": "PASTE_VALID_OBJECT_ID_HERE"
}